reference_looks = [
    {
        "id": "look_001",
        "name": "Layered Bob",
        "description": "Soft layered bob that adds shape and light volume.",
        "suitableFaceShapes": ["oval", "round", "heart"],
        "suitableHairTypes": ["straight", "wavy"],
        "suitableHairLengths": ["short", "medium"],
        "styleGoals": ["low_maintenance", "professional", "volume"],
        "recommendedStyles": ["Layered Bob", "Blow Dry"],
    },
    {
        "id": "look_002",
        "name": "Long Soft Waves",
        "description": "Loose flowing waves for a polished but trendy look.",
        "suitableFaceShapes": ["oval", "heart", "diamond"],
        "suitableHairTypes": ["wavy", "curly"],
        "suitableHairLengths": ["medium", "long"],
        "styleGoals": ["trendy", "professional"],
        "recommendedStyles": ["Textured Lob", "Hair Spa", "Blow Dry"],
    },
    {
        "id": "look_003",
        "name": "Textured Lob",
        "description": "Shoulder-length textured lob for movement and easy styling.",
        "suitableFaceShapes": ["round", "square", "oval"],
        "suitableHairTypes": ["straight", "wavy"],
        "suitableHairLengths": ["medium"],
        "styleGoals": ["low_maintenance", "trendy"],
        "recommendedStyles": ["Textured Lob", "Blow Dry"],
    },
    {
        "id": "look_004",
        "name": "Defined Curly Cut",
        "description": "Shape-focused curly cut that enhances natural curl definition.",
        "suitableFaceShapes": ["oval", "heart", "oblong"],
        "suitableHairTypes": ["curly", "coily"],
        "suitableHairLengths": ["short", "medium", "long"],
        "styleGoals": ["volume", "low_maintenance"],
        "recommendedStyles": ["Defined Curly Cut", "Deep Conditioning"],
    },
    {
        "id": "look_005",
        "name": "Sleek Straight Layers",
        "description": "Smooth layered style for a clean and professional finish.",
        "suitableFaceShapes": ["oval", "square", "oblong"],
        "suitableHairTypes": ["straight"],
        "suitableHairLengths": ["medium", "long"],
        "styleGoals": ["professional", "trendy"],
        "recommendedStyles": ["Sleek Layers", "Blow Dry", "Keratin Treatment"],
    },
    {
        "id": "look_006",
        "name": "Repair-Focused Trim",
        "description": "Healthy trim and treatment-first recommendation for damaged hair goals.",
        "suitableFaceShapes": ["oval", "round", "square", "heart", "diamond", "oblong"],
        "suitableHairTypes": ["straight", "wavy", "curly", "coily"],
        "suitableHairLengths": ["short", "medium", "long"],
        "styleGoals": ["repair"],
        "recommendedStyles": ["Trim", "Deep Conditioning", "Hair Spa"],
    },
]